dist: trusty
sudo: required
language: python
env:
  global:
  - secure: FzrE07dPOiU8EI0+SiDvi4yEEjJlfCksssaeaK8NF9ZXRv12uBT4WhNN/j89jfYJn//8L6imy13d9Wa9RiW/oCploMH5uhtehl/QUdKxW68qKrd7+fcWJ/4/yiNJ9YVykPBKohRRt91kzu6S9688EeeOJKoP+8BvQBatpYjAHH3gGxThS8BEUbQ2fJ9V0spyxpZI+5xuGVKKogdd293BgbqNhSeug+vzF+FIAp5CKbwez2nEK2GlG2R83dN7uMO9QkP8G8dguJuc0h4MPcyVw1AKWRQPZs8rF9B+jzpi2DTuzuY91lv+ARBy2zWsshg/HbkS+KwhLo70gqqOXVCPCtJKMb75LfjbrZrFPHBaqy8yScJQaxLsDWWcOp39uzIPyzWbQVgsWWrfDlV+zeNntTxhx3+ndCNu7kL8ZarR/ykgNQB8AvzZTKDmX+z0Nh4Hew4WzfVN2TyQZ3KFgocOUZp5B2ss+KRdEBfKSjhGYwB76ObRA7FKwuxvS8KZIoxdt4TtWYxTa0DQ0HdWukyfC6SXC3OgKIHDs7NSp7U1Tx2UZx8+KUlWYwbyKyeWavVZgxA4Os1ltz2McyuD2Qjhy4UynWKAx8dMjIsBHHKnFIY2C0yRhP1I8mrsQ1S4tCdaNEEedDb02uMCIt+mtAOeYmyThs3/b4ZXWJ3J+WkBqWo=
python:
  - '3.4'
  - '3.5'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libcgraph6 graphviz
install: pip install -e .[dev]
script: py.test -s -v || true
after_success:
  - 'test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && curl -H
    "Content-Type: application/json" -X POST https://registry.hub.docker.com/u/li3ds/li3ds/trigger/$DOCKER_API_KEY/'
